### ISSUE TITLE
module attribute error

### ISSUE THREAD

**Issue by joehene** [shantnu/FaceDetect#12]
Hi?
I am getting an error on running the command

Traceback (most recent call last):
  File "face_detect.py", line 21, in <module>
    flags = cv2.cv.CV_HAAR_SCALE_IMAGE
AttributeError: 'module' object has no attribute 'cv'

**Comment by arawal** [comment]
Looks like you can go around the error by just removing the flags field. Still seems to work.
@shantnu : Why do we need that field?

**Comment by shantnu** [comment]
The code supports both opencv2 and 3. The flag is needed for one of them.
