### ISSUE TITLE
AttributeError: module 'cv2' has no attribute 'CV_HAAR_SCALE_IMAGE'

### ISSUE THREAD

**Issue by Qwyrp** [shantnu/FaceDetect#20]
File "face_detect.py", line 21, in <module> 
flags = cv2.CV_HAAR_SCALE_IMAGE AttributeError: 
module 'cv2' has no attribute 'CV_HAAR_SCALE_IMAGE'

I've replaced it with cv2.CASCADE_SCALE_IMAGE and now it works like a charm !

**Comment by psychon7** [comment]
AttributeError                            Traceback (most recent call last)
<ipython-input-2-bd5febf8e07f> in <module>
     19     minNeighbors=5,
     20     minSize=(30, 30),
---> 21     flags = cv2.cv.CV_HAAR_SCALE_IMAGE
     22 )
     23 

AttributeError: module 'cv2.cv2' has no attribute 'cv'
