### ISSUE TITLE
AttributeError: module 'cv2.cv2' has no attribute 'cv'

### ISSUE THREAD

**Issue by psychon7** [shantnu/FaceDetect#21]
AttributeError                            Traceback (most recent call last)
<ipython-input-2-bd5febf8e07f> in <module>
     19     minNeighbors=5,
     20     minSize=(30, 30),
---> 21     flags = cv2.cv.CV_HAAR_SCALE_IMAGE
     22 )
     23 

AttributeError: module 'cv2.cv2' has no attribute 'cv'

**Comment by Elect96** [comment]
Hey!
Just delete/comment that line and it should work wonders.

~Elect96

**Comment by xkrava02** [comment]
You can just **delete that line** and it will work

**Comment by panchiwalashivani** [comment]
You have to Import the contrib library 

**pip install opencv-contrib-python**

or

**pip3 install opencv-contrib-python**

Then it will work.
