### ISSUE TITLE
cv2.error: OpenCV(4.1.1) /io/opencv/modules/objdetect/src/cascadedetect.cpp:1689: error: (-215:Assertion failed) !empty() in function 'detectMultiScale'

### ISSUE THREAD

**Issue by iliavar** [shantnu/FaceDetect#26]
i was running this script(live.py) and the i got this error:

cv2.error: OpenCV(4.1.1) /io/opencv/modules/objdetect/src/cascadedetect.cpp:1689: error: (-215:Assertion failed) !empty() in function 'detectMultiScale'

how can i solve this problem?
tnx for answers

**Comment by danielrojas08** [comment]
I have the same problem
Please Help Me
I'm just starting in this field of development, and I'm new to this type of code

**Comment by daveashu** [comment]
hope you have resolved your issue by now, if not i had same issue. 
it's real classic and feels very strange too. 
you need to make sure that you are loading the correct haar-classifier file.
to check that i ran below code and realized that it wasn't getting loaded. 

faceCascade = cv2.CascadeClassifier(cv2.data.haarcascades + "haarcascade_smile.xml")
print(cv2.CascadeClassifier.empty(faceCascade) )

so you need to give correct location of the file. if print statement returns 'False' you good if not then there is something wrong with your path which classifier cannot find while loading. 

hope this helps

**Comment by Kamuri-chan** [comment]
> 
> 
> hope you have resolved your issue by now, if not i had same issue.
> it's real classic and feels very strange too.
> you need to make sure that you are loading the correct haar-classifier file.
> to check that i ran below code and realized that it wasn't getting loaded.
> 
> faceCascade = cv2.CascadeClassifier(cv2.data.haarcascades + "haarcascade_smile.xml")
> print(cv2.CascadeClassifier.empty(faceCascade) )
> 
> so you need to give correct location of the file. if print statement returns 'False' you good if not then there is something wrong with your path which classifier cannot find while loading.
> 
> hope this helps

even when its return 'True', still giving the same error :sob:

**Comment by Karan-Ghatt** [comment]
I seem to be facing the same issue, the print statement returns false but I still keep running into the following error: 

faces = faceCascade.detectMultiScale(
cv2.error: OpenCV(4.2.0) C:\projects\opencv-python\opencv\modules\objdetect\src\cascadedetect.cpp:1689: error: (-215:Assertion failed) !empty() in function 'cv::CascadeClassifier::detectMultiScale'

Any insight would be greatly appreciated!

**Comment by Crankb** [comment]
Try adding 'cascades/' before the xml
faceCascade = cv2.CascadeClassifier("cascades/haarcascade_smile.xml")
print(cv2.CascadeClassifier.empty(faceCascade))

**Comment by Isha-kumar** [comment]
I am facing the same issue recently, I am new to this working on eye detection can anyone help me with this?
i am using opencv 4.7.0 version

Code:  
 eyes_cascade = cv2.CascadeClassifier('cascades/haarcascade_eye.xml')  
    RGB_frame = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
    try:
        eyes = eyes_cascade.detectMultiScale(RGB_frame,scaleFactor=1.1, minNeighbors=5, minSize=(30, 30))
    except Exception as e:
        print(f"Error in detectMultiScale: {e}")
Error:
Error in detectMultiScale: OpenCV(4.7.0) D:\a\opencv-python\opencv-python\opencv\modules\objdetect\src\cascadedetect.cpp:1689: error: (-215:Assertion failed) !empty() in function 'cv::CascadeClassifier::detectMultiScale'

I have even checked for verification of xml file print statement is returning true
faceCascade = cv2.CascadeClassifier("cascades/haarcascade_eye.xml")
print(cv2.CascadeClassifier.empty(faceCascade))
