### ISSUE TITLE
cv2.error: OpenCV(4.2.0) ../modules/core/src/persistence.cpp:719: error: (-49:Unknown error code -49) Input file is invalid in function 'open'

### ISSUE THREAD

**Issue by kravenor** [shantnu/FaceDetect#27]
When I try to execute the example i have this output :
`cv2.error: OpenCV(4.2.0) ../modules/core/src/persistence.cpp:719: error: (-49:Unknown error code -49) Input file is invalid in function 'open'`

`The above exception was the direct cause of the following exception:
`
```
Traceback (most recent call last):
  File "face.py", line 9, in <module>
    faceCascade = cv2.CascadeClassifier(cascPath)
SystemError: <class 'cv2.CascadeClassifier'> returned a result with an error set

```

How i can fix it?

**Comment by baronrustamov** [comment]
same thing
