### ISSUE TITLE
module 'cv2' has no attribute '__version__'

### ISSUE THREAD

**Issue by GeneratorX16** [shantnu/FaceDetect#33]
OpenCV version: 4.5.3
Python Version:3.7
Windows 10

I installed opencv using cmake and visual studio and when I run python on cmd and type out the code:
>>> import cv2
>>> print(cv2.__version__)

I get this error:

Traceback (most recent call last):
  File <stdin>, line 1, in <module>
AttributeError: module 'cv2' has no attribute '__version__'

Edit: There are double underscores before and after version but I cant seem to see them in the post.

**Comment by YilanWang** [comment]
how to solve it？
