### ISSUE TITLE
difference between this cascade file and the one packaged by opencv

### ISSUE THREAD

**Issue by dashesy** [shantnu/FaceDetect#4]
The `haarcascade_frontalface_default.xml` file here is different from same file packaged by OpenCV (in `/usr/share/OpenCV/haarcascades/haarcascade_frontalface_default.xml`). 
The size is smaller, but a diff does not say anything useful.

It would help to know if it is a different version, or has some improvements over the upstream, thanks.

**Comment by shantnu** [comment]
It's the same file, taken from the version of open cv I developed on. I'm guessing the newer open cv version has something extra, but since it will be backwards compatible ( or should be), there won't be any real differences.
